### ISSUE TITLE
benchmark it against https://github.com/Boostport/mjml-go

### ISSUE THREAD

**Issue by gedw99** [TcMits/mjml2html#3]
hey @TcMits thanks for making this.

https://github.com/Boostport/mjml-go is the wasm version. Wondering why you chose the nodes approach ?

**Comment by TcMits** [comment]
hi @gedw99 , because it is simpler than wasm version. You don't need a worker pool or something else.

https://github.com/TcMits/mjml2html/blob/ba300961ef65585e0551b78bfedeb91aacc97d02/mjml2html_test.go#L70-L160
```sh
$ go test -bench=. -benchtime=10s
goos: darwin
goarch: amd64
pkg: github.com/TcMits/mjml2html
cpu: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
Benchmark_ToHTML-8                   202          59646052 ns/op
Benchmark_ToHTML_Parallel-8          418          27818648 ns/op
PASS
ok      github.com/TcMits/mjml2html     33.622s
```
